### ISSUE TITLE
Scan height gets 'cached' across multiple wallet opens

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-electron#60]
### Steps to reproduce

* Import a wallet (I did it via seed)
* Set a scan height of 1 million
* Close wallet (but not program)
* Import a wallet (I did it via keys)
* Don't set a scan height
* Open wallet
* Wallet will start scanning from 1 million

Furthermore, setting a scan height of 0 doesn't work, due to the logic [here](https://github.com/turtlecoin/turtle-wallet-electron/blob/fbaf0006c11ebda17556f2498bf263e9c6b434fa/src/js/ws_manager.js#L505).
Setting the scan height to 1337 worked as expected.

**Comment by rixombea** [comment]
@zpalmtree I logged scanheight value passed to turtle-service and unable to reproduce the cached scan height issue.

for scan height of <1024, fixed in 45dcbfca2705c07058b61d815d9946b4048ef996

for scan height value of 0, isn't the default value for scanheight is [0](https://github.com/turtlecoin/turtlecoin/blob/5be732b993509bf870bc1ffb5af8536a6df036e0/src/WalletService/WalletServiceConfiguration.cpp#L47)? scanheight value <=0 are ignored, and no `scan-height` argument will be passed to turtle-service at all, so I thought it will use 0 as a value.

**Comment by zpalmtree** [comment]
I can't reproduce any more either, I don't know if your previous commits changed the logic.

Though, when checking the generated config file, I couldn't see the scan height argument in there, even when using a scan height - and the scan height worked. I didn't see it in the turtle-service launch options either, so not sure what was happening there.
